from . import academics_courses
from . import academics_cycles_by_section
from . import academics_departments
from . import academics_enroll_students_into_sections
from . import academics_master_schedule
from . import academics_schedule_set
from . import academics_schedule_sets_by_level
from . import academics_sections_by_school_level
from . import core_levels
from . import core_roles
from . import core_terms
from . import core_years
from . import legacy_list
from . import users_addresses_by_user
from . import venues_buildings
